# create transactions
POST http://localhost:8080/transactions
Content-Type: application/json

{
    "prompt": "Eu tomei cafe da manha e paguei 15,00"
}

###

# get transactions recents
GET http://localhost:8080/transactions/recent

###

# get transactions
GET http://localhost:8080/transactions?name=&categories=&pageIndex=0